import './globals.css'

import { cookies } from 'next/headers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const cookie = cookies().get('mode')

  return (
    <html lang="en">
      <body
        className={
          cookie != undefined && cookie.value === 'dark' ? 'dark-mode' : ''
        }
      >
        {children}
      </body>
    </html>
  )
}
