import './globals.css'
import Link from 'next/link'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <div className="linkWrapper">
            <Link href="/">홈</Link>
          </div>
          <div className="linkWrapper">
            <Link href="/list">List</Link>
          </div>
          <div className="linkWrapper">
            <Link href="/join">회원가입</Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  )
}
