#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
echo "Feature branch merged into develop. Running automation..."
echo "husky $HUSKY_GIT_STDIN"
if [ "$HUSKY_GIT_STDIN" == "refs/heads/develop" ]; then
  echo "Feature branch merged into develop. Running automation..."

  # 여기에 원하는 작업을 추가합니다.
  # 예: 빌드 실행, 푸시, 머지 등

  # 빌드 스크립트 실행
  echo "Running build script..."
  pnpm build  # 또는 적절한 빌드 명령어

  if [ $? -eq 0 ]; then
    echo "Build successful. Pushing to develop..."
    git push origin develop

    # develop 브랜치로부터 main 브랜치로 머지
    git checkout main
    git merge develop

    if [ $? -eq 0 ]; then
      echo "Merge into main successful. Pushing to main..."
      git push origin main
    else
      echo "Merge into main failed. Aborting the push to main."
    fi
  else
    echo "Build failed. Aborting the push to develop."
  fi
fi
