#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 색상 코드
RED='\033[0;31m'
GREEN='\033[0;32m'
BOLD='\033[1m'
RESET='\033[0m'

BRANCH_NAME=`git rev-parse --abbrev-ref HEAD`

echo "${BOLD}Current Branch Name"
echo "${BOLD}====================================="
echo "${BOLD}$BRANCH_NAME"
echo "${BOLD}====================================="

if [ "$BRANCH_NAME" = "develop"  ]; then
  echo "${RED}Feature branch merged into develop. Running automation..."

  # 여기에 원하는 작업을 추가합니다.
  # 예: 빌드 실행, 푸시, 머지 등

  # 빌드 스크립트 실행
  echo "Running build script..."
  pnpm build  # 또는 적절한 빌드 명령어

  if [ $? -eq 0 ]; then
    echo "${GREEN}Build successful. Pushing to develop..."
    git push origin develop
  else
    echo "${RED}Build failed. Aborting the push to develop."
  fi
fi
