#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BRANCH_NAME=`git rev-parse --abbrev-ref HEAD`

# 색상 코드 정의
RED='\033[1;31m'
GREEN='\033[1;32m'
BOLD='\033[1m'
RESET='\033[0m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'

echo "${YELLOW}Current Branch Name"
echo "${YELLOW}====================================="
echo "${YELLOW}$BRANCH_NAME"
echo "${YELLOW}====================================="

if [ "$BRANCH_NAME" = "develop"  ]; then
  echo "${BOLD}Feature branch merged into $BRANCH_NAME. Running automation...${RESET}"

  # 빌드 스크립트 실행
  echo "${BOLD}Running build script...${RESET}"
  pnpm build  # 또는 적절한 빌드 명령어

  if [ $? -eq 0 ]; then
    echo "${BLUE}Build successful. Pushing to develop...${RESET}"
    git push origin develop


  else
    echo "${RED}Build failed. Aborting the push to develop."
  fi
elif [ "$BRANCH_NAME" = "main" ]; then
    # main 브렌치에 Merge 되었을때
    echo "${BOLD}Develop merged into $BRANCH_NAME. Running automation...${RESET}"

    git push origin main

    echo "${BLUE}Automation for main branch push Complete.${RESET}"
  else
    echo "${RED}Push Failed. Aborting the push to develop${RESET}"
fi