#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

COMMIT_EDITMSG=$1

addBranchNumber() {
    
  NAME=$(git branch | grep '*' | sed 's/* //' | sed 's/^.*\///') 
  ISSUE_NUMBER=`echo $NAME | cut -d '-' -f1`
  echo "[#$ISSUE_NUMBER] $(cat $COMMIT_EDITMSG)" > $COMMIT_EDITMSG
}

MERGE=$(cat $COMMIT_EDITMSG|grep -i 'merge'|wc -l)

if [ $MERGE -eq 0 ] ; then
  addBranchNumber
fi